In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('./data.csv')

In [3]:
data.head(5)

,nameSeller,emailSeller,userId,count,productId,price,pricePerM2,categoryId,cityCode,districtId,...,Ngày đăng,Ngày hết hạn,Loại tin,Mã tin,Hướng ban công,Số tầng,Mặt tiền,Đường vào,Pháp lý,Hướng nhà
0,Hùng Sơn Hifriendz,nguyenhungsonne@gmail.com,3051805,20,40577160,3800000,95000.000000,57,SG,69,...,19/11/2024,29/11/2024,Tin thường,40577160,NaN,NaN,NaN,NaN,NaN,NaN
1,Hùng Sơn Hifriendz,nguyenhungsonne@gmail.com,3051805,20,40984555,7600000,138181.818182,57,SG,69,...,19/11/2024,29/11/2024,Tin thường,40984555,NaN,NaN,NaN,NaN,NaN,NaN
2,Nghĩa - Dylan Unite Group,trantatnghia2105@gmail.com,2541791,20,40704688,6000000,171428.571429,57,SG,66,...,31/10/2024,01/12/2024,Tin thường,40704688,NaN,NaN,NaN,NaN,NaN,NaN
3,Nghĩa - Dylan Unite Group,trantatnghia2105@gmail.com,2541791,20,39875251,6500000,162500.000000,57,SG,66,...,18/11/2024,18/12/2024,Tin thường,39875251,NaN,NaN,NaN,NaN,NaN,NaN
4,Hưng,infosunny10@gmail.com,225063,20,36192033,5600000,215384.615385,57,HN,7,...,19/11/2024,19/12/2024,Tin thường,36192033,Đông - Nam,NaN,NaN,NaN,NaN,NaN

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 703 entries, 0 to 702
Data columns (total 42 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nameSeller      703 non-null    object
 1   emailSeller     551 non-null    object
 2   userId          703 non-null    int64
 3   count           703 non-null    int64
 4   productId       703 non-null    int64
 5   price           703 non-null    int64
 6   pricePerM2      703 non-null    float64
 7   categoryId      703 non-null    int64
 8   cityCode        703 non-null    object
 9   districtId      703 non-null    int64
 10  streetId        703 non-null    int64
 11  wardId          703 non-null    int64
 12  projectId       703 non-null    int64
 13  productType     703 non-null    int64
 14  area            703 non-null    float64
 15  latitude        703 non-null    float64
 16  longitude       703 non-null    float64
 17  Link            703 non-null    object
 18  Title           703 non-null    object
 19  Address         703 non-null    object
 20  Verified        27 non-null     object
 21  Images          694 non-null    object
 22  Mức giá         703 non-null    object
 23  Mức giá ext     0 non-null      float64
 24  Diện tích       703 non-null    object
 25  Diện tích ext   0 non-null      float64
 26  Phòng ngủ       437 non-null    object
 27  Phòng ngủ ext   0 non-null      float64
 28  Detail          703 non-null    object
 29  Số phòng ngủ    437 non-null    object
 30  Số toilet       477 non-null    object
 31  Nội thất        514 non-null    object
 32  Ngày đăng       703 non-null    object
 33  Ngày hết hạn    703 non-null    object
 34  Loại tin        703 non-null    object
 35  Mã tin          703 non-null    int64
 36  Hướng ban công  65 non-null     object
 37  Số tầng         67 non-null     object
 38  Mặt tiền        27 non-null     object
 39  Đường vào       54 non-null     object
 40  Pháp lý         162 non-null    object
 41  Hướng nhà       82 non-null     object
dtypes: float64(7), int64(11), object(24)
memory usage: 230.8+ KB

<h3>Giải thích các giá trị</h3>

- nameSeller : Người cho thuê
- emailSeller : Email của người cho thuê
- userID : Mã id của người cho thuê
- count :
- productId : ID của phòng trọ cho thuê
- price : Giá thuê
- pricePerM2 : Giá thuê / m2
- categoryId : 
- cityCode :       
- districtId :      
- streetId :        
- wardId :          
- productType :     
- area :           
- latitude :     
- longitude :
- Link :           
- Title :           
- Address :        
- Verified :       
- Images :         
- Mức giá :        
- Mức giá ext :   
- Diện tích :      
- Diện tích ext : 
- Phòng ngủ :      
- Phòng ngủ ext : 
- Detail : Thông tin bổ sung         
- Số phòng ngủ :   
- Số toilet :      
- Nội thất :       
- Ngày đăng :      
- Ngày hết hạn :   
- Loại tin :       
- Mã tin :          
- Hướng ban công : 
- Số tầng :        
- Mặt tiền :       
- Đường vào :      
- Pháp lý :        
- Hướng nhà :